quiz/urls.py
from django.urls import path
from quiz.views import (
    FrontPageView, QuizDetailView, CategoryDetailView, QuizGameView,
    CalculateGameScore, ViolationsListView, ViolationsDetailView,
    ViolationReportCreateView
)

urlpatterns = [
    path("", FrontPageView.as_view(), name="index"),
    path("quiz/<int:pk>", QuizDetailView.as_view(), name="quiz_detail"),
    path("quiz/<int:pk>/play", QuizGameView.as_view(), name="quiz_game"),
    path("quiz/<int:pk>/calculate", CalculateGameScore.as_view(), name="calculate_score"),
    path("category/<int:pk>", CategoryDetailView.as_view(), name="category_detail"),
    path("violations", ViolationsListView.as_view(), name="violations_list"),
    path("violation/<int:pk>", ViolationsDetailView.as_view(), name="violation_detail"),
    path("report-abuse/<int:pk>", ViolationReportCreateView.as_view(), name="report_abuse"),
]

stx_quizes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(("quiz.urls", "quiz"), namespace="quiz")),
    path('users/', include(("users.urls", "users"), namespace="users"))
]

quiz/models.py
from django.db import models
from django.db.models import F
from django.contrib.auth.models import User


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=32, unique=True)

    def __str__(self):
        return f"Category {self.name}"


class Quiz(models.Model):
    # Example values
    # Purpose: prevent users from making quizes that will not be
    # playable (1 question with 1 option or inifnitely many options per question).
    # The purpose is to use these variables
    MIN_NUMBER_QUESTIONS = 3
    MAX_NUMBER_QUESTION = 20

    DIFFICULTY_LEVELS = (
        (0, 'easy'),
        (1, 'medium'),
        (2, 'hard'),
    )

    title = models.CharField(max_length=50, unique=True)
    description = models.CharField(
        max_length=200, blank=True, null=True,
        help_text="Few words about the quiz"
    )
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    categories = models.ManyToManyField(Category)
    difficulty = models.IntegerField(choices=DIFFICULTY_LEVELS)
    times_played = models.IntegerField(default=0)
    
    # Set to True after ViolationNtification was sent (see save method)
    # Usage: if true do not include this quiz in public listings (e.g. home page)
    under_moderation = models.BooleanField(default=False)
    # Set to True after mod decides that quiz is offending
    removed = models.BooleanField(default=False)

    def __str__(self):
        return f"Quiz {self.title}"

    def top_scores(self, limit=10):
        return self.scores.order_by('-score_value')[:limit]


class Question(models.Model):
    # Example values
    # Purpose: see Quiz class
    MIN_NUMBER_OPTIONS = 2
    MAX_NUMBER_OPTIONS = 4

    question_text = models.CharField(max_length=100)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, related_name="questions")

    def __str__(self):
        return f"Question {self.question_text}"


class Option(models.Model):
    answer_text = models.CharField(max_length=100)
    is_correct = models.BooleanField(default=False)
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name="options")

    def __str__(self):
        return f"Option {self.answer_text}"


class QuizScore(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, related_name="scores")
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    score_value = models.FloatField(default=0.0)
    date_finished = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Score {self.pk}"

    def save(self, *args, **kwargs):
        super(QuizScore, self).save(*args, **kwargs)
        # Update number of games for this quiz
        related_quiz = Quiz.objects.get(id=self.quiz.id)
        related_quiz.times_played = F('times_played') + 1
        related_quiz.save()
        # Update user's total score
        related_profile = User.objects.get(id=self.user.id).profile
        related_profile.total_score = F('total_score') + self.score_value
        related_profile.save()


class ViolationNotification(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    description = models.TextField(max_length=400)
    timestamp = models.DateTimeField(auto_now_add=True)
    is_closed = models.BooleanField(default=False)
    assigned_to = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def _choose_moderator(self):
        '''Assigns notification to moderator with the least active notifications.'''
        moderators = User.objects.filter(profile__is_moderator=True).all()
        number_assigned_per_mod = min([
            (len(mod.profile.assigned_notifications(active=True)), mod.pk)
            for mod in moderators
        ])
        return User.objects.get(id=number_assigned_per_mod[1])


    def save(self, *args, **kwargs):
        closing = False
        # Need to do this, because super().save() raises
        # an error with additional kwargs passed in.
        try:
            closing = kwargs.pop('closing')
        except KeyError:
            pass
        if not closing:
            # Assign to moderator, only when creating new notification
            mod = self._choose_moderator()
            self.assigned_to = mod
        super(ViolationNotification, self).save(*args, **kwargs)
        if not closing:
            # Set moderation flag, only when creating new notification
            related_quiz = Quiz.objects.get(id=self.quiz.id)
            related_quiz.under_moderation = True
            related_quiz.save()

    def dismiss(self):
        self.is_closed = True
        self.save(closing=True)
        related_quiz = Quiz.objects.get(id=self.quiz.id)
        related_quiz.under_moderation = False
        related_quiz.save()

    def accept(self):
        self.is_closed = True
        self.save(closing=True)
        related_quiz = Quiz.objects.get(id=self.quiz.id)
        related_quiz.under_moderation = False
        related_quiz.removed = True
        related_quiz.save()


    def __str__(self):
        return f"Violation notification {self.pk}"

quiz/views.py
import json
from django.http import request
from django.urls import reverse_lazy
from django.shortcuts import render, redirect, reverse
from django.views.generic import ListView, DetailView, View, CreateView
from quiz.models import Quiz, Category, Option, QuizScore, User, ViolationNotification
from django.contrib.auth.mixins import LoginRequiredMixin

from users.mixins import ModeratorOnlyMixin
# Create your views here.


class FrontPageView(ListView):
    model = Quiz
    template_name = "index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        context['most_popular'] = Quiz.objects.filter(removed=False).filter(under_moderation=False).order_by('-times_played')[:5]
        return context


class QuizDetailView(DetailView):
    model = Quiz
    template_name = "quiz_detail.html"


class CategoryDetailView(DetailView):
    model = Category
    template_name = "category_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['other_categories'] = Category.objects.exclude(pk=self.kwargs['pk'])
        return context


class QuizGameView(LoginRequiredMixin, DetailView):
    login_url = '/users/login'
    model = Quiz
    template_name = "quiz_game.html"


class CalculateGameScore(View):
    def post(self, request, *args, **kwargs):
        points = 0
        game_data = json.loads(request.body)['formData']
        for answer in game_data:
            option = Option.objects.get(id=answer['option_id'])
            if option.is_correct:
                points += 100/answer['answer_time']
        new_quiz_score = QuizScore(
            quiz=Quiz.objects.get(pk=self.kwargs['pk']),
            user=User.objects.get(id=request.user.id),
            score_value=points,
        )
        new_quiz_score.save()
        return redirect('quiz:quiz_detail', pk=self.kwargs['pk'])


class ViolationsListView(ModeratorOnlyMixin, ListView):
    model = ViolationNotification
    template_name = 'violations_list.html'
    context_object_name = 'violations'

    def get_queryset(self):
        user = self.request.user
        if not user.profile.is_moderator:
            return None
        return user.profile.assigned_notifications(active=True)


class ViolationsDetailView(ModeratorOnlyMixin, DetailView):
    model = ViolationNotification
    template_name = 'violation_detail.html'
    context_object_name = 'violation'

    def post(self, request, *args, **kwargs):
        report_id = int(self.request.POST.get('id'))
        decision = self.request.POST.get('decision').lower()
        
        violation_report = ViolationNotification.objects.get(id=report_id)
        if violation_report is not None:
            if decision == 'accept':
                violation_report.accept()

            if decision == 'dismiss':
                violation_report.dismiss()

        return redirect('quiz:violations_list')

class ViolationReportCreateView(CreateView):
    model = ViolationNotification
    fields = ('description',)
    template_name = 'report_abuse.html'

    def get_success_url(self):
        return reverse('quiz:index')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['quiz'] = Quiz.objects.get(id=self.kwargs['pk'])
        return context

    def form_valid(self, form):
        quiz = Quiz.objects.get(id=self.kwargs['pk'])
        self.object = form.save(commit=False)
        self.object.quiz = quiz
        return super(ViolationReportCreateView, self).form_valid(form)

quiz/templates/category_detail.html
{% extends 'base.html' %}

{% block title %}

{% endblock title %}

{% block template_styles %}
<style>
.quiz-card {
    font-size: 1rem;
    padding: 10px 5px;
}

#all-quizes {
    width: 100%;
    display: flex;
    flex-flow: row wrap;
}
</style>
{% endblock template_styles %}

{% block content %}
<div class="detail-container">
    <div class="category-detail">
        <h1>You are viewing all quizes of category: {{ category.name }}</h1>
        <div id="all-quizes">
        {% for quiz in category.quiz_set.all %}
            <a href="{% url 'quiz:quiz_detail' quiz.id %}" class="quiz-card">{{ quiz.title }}</a>
        {% endfor %}
        </div>
    </div>
    <div id="other-categories">
        <h1>See other categories</h1>
        {% for category in other_categories %}
            <a href="{% url 'quiz:category_detail' category.id %}" class="btn">{{ category.name }}</a>
        {% empty %}
            <p>No categories yet...</p>
        {% endfor %}
    </div>
</div>
{% endblock content %}

{% block template_scripts %}
{% endblock template_scripts %}

quiz/templates/index.html
{% extends 'base.html' %}

{% block title %}
{% endblock title %}

{% block content %}
{% if user.profile and user.profile.is_moderator %}
<h1>List of violation reports</h1>
{% with user.profile.assigned_notifications as reports %}
<a href="{% url 'quiz:violations_list' %}" class="btn start-btn">{{ reports|length }} pending</a>
{% endwith %}
{% endif %}
<h1>Choose one from our categories</h1>
<div class="quiz-cards-containter">
            {% for category in categories %}
             <a class="quiz-card main-text" href="{% url 'quiz:category_detail' category.id %}">
                 <h1>{{ category.name }}</h1>
             </a>
             {% empty %}
             <h3>No categories...</h3>
             {% endfor %}
</div>

<h1>or one from our most popular quizes</h1>
<div class="quiz-cards-containter">
            {% for quiz in most_popular %}
                <a class="quiz-card" href="{% url 'quiz:quiz_detail' quiz.id %}">
                    <h1 class="main-text">{{ quiz.title }}</h1>
                    <p class="sub-text">Difficulty: {{ quiz.get_difficulty_display }}</p>
                </a>
            {% empty %}
                <h3>No categories...</h3>
            {% endfor %}
</div>
{% endblock content %}

quiz/templates/quiz_detail.html
{% extends 'base.html' %}

{% block title %}

{% endblock title %}

{% block template_styles %}
<style>
table.leaderboard {
    margin: 10px auto;
    border-collapse: collapse;
    width: 100%;
}

td, th {
    border: 1px solid #999;
    padding: 0.5rem;
    text-align: center;
}

.quiz-details > * {
    margin: 5px;
}

</style>
{% endblock template_styles %}

{% block content %}
<div class="detail-container">
    <div class="quiz-details">
        <h1 class="main-text" id="quiz-title">Quiz title: {{ quiz.title }}</h1>
        <div class="tag {{ quiz.get_difficulty_display }}">{{ quiz.get_difficulty_display }}</div>
        <p class="sub-text"> submited by: {{ quiz.author }}</p>
        {% if quiz.description %}
        <p class="sub-text" id="quiz-description">
            {{ quiz.desription }}
        </p>
        {% endif %}
        <p>Played {{ quiz.times_played }} time{{ quiz.times_played|pluralize }}</p>
        <a href="{% url 'quiz:quiz_game' quiz.id %}" class="btn start-btn">Play!</a>
        <div id="other-quizes">
            <h2>See other quizes of that type:</h2>
            {% for category in quiz.categories.all %}
                <a class="btn" href="{% url 'quiz:category_detail' category.id %}">
                    {{ category.name }}
                </a>
            {% endfor %}
        </div>
    </div>
    <div id="leaderboard">
        <h1 class="main-text">Leaderboard:</h1>
        {% if quiz.scores %}
        <table class="leaderboard">
            <thead>
                <th>#</th>
                <th>username</th>
                <th>score</th>
                <th>date</th>
            </thead>
            <tbody>
            {% for score in quiz.top_scores %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ score.user.username }}</td>
                    <td>{{ score.score_value|floatformat:2 }}</td>
                    <td>{{ score.date_finished }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        {% else %}
            <p>There are no scores yet..</p>
        {% endif %}
    </div>
    <div>
        <a href="{% url 'quiz:report_abuse' quiz.pk %}" class="btn">Report abuse</a>
    </div>
</div>
{% endblock content %}

{% block template_scripts %}
{% endblock template_scripts %}

quiz/templates/quiz_game.html
{% extends 'base.html' %}
{% block title %} {{quiz.name}}{% endblock title %}
{% block template_styles %}
<style>
body {
    overflow-x: hidden;
}
.form-container {
    width: 100%;
    display: flex;
    flex-flow: column;
    justify-content: center;
    align-items: center;
    position: absolute;
    left: -3000px;
    transition: all 0.3s ease-in-out;
}

.form-container.form__active {
    transform: translateX(3000px)
}

.form-container.form__inactive {
    transform: translateX(6000px)
}

/* .form-container .panel__active {
    transform: translateX(-6000px)
} */

.form-container > * {
    margin: 5px;
    border-radius: 5px;
    padding: 10px 25px;
}


.form-container .answers_container {
    display: flex;
    flex-flow: row wrap;
    justify-content: center;
    align-items: center;
}

.form-container .answers_container > button.answer_btn {
    flex: 0 34%;
    margin: 10px;
    padding: 20px 10px;
}

span.timer {
    display: inline-block;
    font-size: 2rem;
}
</style>
{% endblock template_styles %}
{% block content %}
{% if quiz %}
<div id="stage0" class="form-container">
  <button id="start-btn" class="btn start-btn">Start game!</button>
</div>
{% for question in quiz.questions.all %}
  <div id="stage{{question.id}}" class="form-container" data-question_id={{question.id}}>
    <span class="timer">20</span>
    <span class="question-title">{{ question.question_text|safe }}</span>
    <div class="answers_container">
        {% for option in question.options.all %}
          <button class="answer_btn" value="{{option.id}}">{{option.answer_text|safe}}</button>
        {% endfor %}
    </div>
  </div>
{% endfor %}
{% else %}
  <p>No items available.</p>
{% endif %}

{% endblock content %}

{% block template_scripts %}
<script>
  var stages = document.querySelectorAll("div.form-container");
  var current_stage = 0;
  var formData = [];
  var timeleft = 200;

  var start_btn = document.querySelector("button#start-btn")
  if (stages) {
      stages[0].classList.toggle("form__active");
      start_btn.addEventListener("click", function () {
          nextStage();
      });
  }


  function nextStage() {
      if (current_stage < stages.length - 1) {
          let ans_btns = stages[current_stage + 1].querySelectorAll("button.answer_btn");
          [].forEach.call(ans_btns, function (btn) {
              btn.addEventListener("click", function () {
                  formData.push({"question_id": stages[current_stage].getAttribute("data-question_id"), "option_id": this.value, "answer_time": 200-timeleft})
                  nextStage();
              });
          });
          stages[current_stage].classList.toggle("form__active");
          stages[current_stage].classList.toggle("form__inactive");
          let timer_container = stages[current_stage + 1].querySelector("span.timer")
          stages[current_stage + 1].classList.toggle("form__active");
          clearInterval(window.timer_func);
          timeleft = 200;
          current_stage += 1;
          timer(timer_container, nextStage);
      } else {
          finishGame();
          clearInterval(window.timer_func);
      }
  }

  function finishGame() {
    console.log({
        "csrfmiddlewaretoken": "{{ csrf_token }}",
        "formData": formData
      })
      postData(url="{% url 'quiz:calculate_score' quiz.pk %}", 
      data={
        "csrfmiddlewaretoken": "{{ csrf_token }}",
        "formData": formData
      })
  }

  function timer(element, button_to_click) {
      window.timer_func = setInterval(function () {
          element.innerHTML = Math.round(timeleft/10);
          timeleft -= 1;
          if (timeleft == 0) {
              clearInterval(timer_func);
              element.innerHTML = "Time's out!"
              if (current_stage < stages.length - 1) {
                  nextStage();
              } else {
                  finishGame();
              }
          }
      }, 100);
  }

async function postData(url = '', data = {}) {
  // Default options are marked with *
  const response = await fetch(url, {
      method: 'POST', // *GET, POST, PUT, DELETE, etc.
      headers: {
          'Content-Type': 'application/json',
          "X-CSRFToken": "{{csrf_token}}"
      },
      redirect: 'follow', // manual, *follow, error
      body: JSON.stringify(data) // body data type must match "Content-Type" header
  });
  return await window.location.replace(response.url);; // parses JSON response into native JavaScript objects
}
</script>
{% endblock template_scripts %}

quiz/templates/report_abuse.html
{% extends 'base.html' %}

{% block title %}
Report quiz for abuse
{% endblock %}

{% block template_styles %}
{% endblock %}

{% block content %}
    <h1>Report violation of rules for quiz <em>{{ quiz.title }}</em></h1>
    <br>
    <form method="POST" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" class="btn start-btn" value="Submit">
    </form>
{% endblock %}

{% block template_scripts %}
{% endblock %}

quiz/templates/violation_detail.html
{% extends 'base.html' %}

{% block title %}
{% endblock %}

{% block template_styles %}
{% endblock %}

{% block content %}
    <div class="quiz-card-container">
        <div class="quiz-card">
            <h1>Violation notification</h1>
            <p><strong>For:</strong></p>
            <p><a href="{% url 'quiz:quiz_detail' violation.quiz.pk %}"><em>{{ violation.quiz.title }}</em></a></p>
            <p><strong>Issued:</strong></p>
            <p>{{ violation.timestamp|date:"Y-m-d H:i" }}</p>
            <p><strong>Reason:</strong></p>
            <p>{{ violation.description }}</p>
            <br>
            <form method="POST" action="">
                {% csrf_token %}
                <input type="submit" class="btn" value="Dismiss" name="decision">
                <input type="submit" class="btn" value="Accept" name="decision">
                <input type="hidden" name="id" value="{{ violation.id }}">
            </form>
        </div>
    </div>
{% endblock %}

{% block template_scripts %}
{% endblock %}

quiz/templates/violations_list.html
{% extends 'base.html' %}

{% block title %}
List of reported quizes
{% endblock %}

{% block template_styles %}
{% endblock %}

{% block content %}
    <div class="quiz-card-container">
    {% for violation in violations %}
        <div class="quiz-card">
            <a href="{% url 'quiz:violation_detail' violation.pk %}">
                Quiz <em>{{ violation.quiz.title }}</em> reported at {{ violation.timestamp|date:"Y-m-d H:i" }}
            </a>
        </div>
    {% empty %}
        <p>No active violation notifications</p>
    {% endfor %}
    </div>
{% endblock %}

{% block template_scripts %}
{% endblock %}