quiz/urls.py
from django.urls import path
from quiz.views import (
    FrontPageView, QuizDetailView, CategoryDetailView, QuizGameView,
    CalculateGameScore, ViolationsListView, ViolationsDetailView,
    ViolationReportCreateView
)

urlpatterns = [
    path("", FrontPageView.as_view(), name="index"),
    path("quiz/<int:pk>", QuizDetailView.as_view(), name="quiz_detail"),
    path("quiz/<int:pk>/play", QuizGameView.as_view(), name="quiz_game"),
    path("quiz/<int:pk>/calculate", CalculateGameScore.as_view(), name="calculate_score"),
    path("category/<int:pk>", CategoryDetailView.as_view(), name="category_detail"),
    path("violations", ViolationsListView.as_view(), name="violations_list"),
    path("violation/<int:pk>", ViolationsDetailView.as_view(), name="violation_detail"),
    path("report-abuse/<int:pk>", ViolationReportCreateView.as_view(), name="report_abuse"),
]

stx_quizes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(("quiz.urls", "quiz"), namespace="quiz")),
    path('users/', include(("users.urls", "users"), namespace="users"))
]

users/urls.py
from django.urls import path, include
from users.views import UserSignUpView, UserLoginView, UserLogoutView, UserProfileView

urlpatterns = [
    path("", include("django.contrib.auth.urls")),
    path("signup", UserSignUpView.as_view(), name="user_signup"),
    path("login", UserLoginView.as_view(), name="login"),
    path("logout", UserLogoutView.as_view(), name="logout"),
    path("profile/<int:pk>", UserProfileView.as_view(), name="user-profile"),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock title %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'base_styles.css' %}" />
    {% block template_styles %}
    {% endblock template_styles %}
  </head>
  <body>
      <header>
        <nav>
            <a class="brand-container" href="{% url 'quiz:index' %}">
                <svg class="brand-logo" viewBox="0 0 70 70" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <ellipse cx="32.5" cy="35.7338" rx="32.5" ry="32.2662" fill="#6B81FA" fill-opacity="0.74"/>
                    <path d="M19.1546 36.2014L28.4363 49.0175C30.5234 51.8994 34.8676 51.7406 36.7387 48.714L65 3" stroke="#D9CB9E" stroke-width="10"/>
                </svg>
                <h1 class="brand-text">STX Quiz</h1>
              </a>
            <button id="dark-switch" class="btn">Dark mode</button>
            {% if user.is_authenticated %} 
              <div class="user-container">
                  <span>Hello, {{user.username}}!</span>
                  <svg id="dropdown-icon" viewBox="0 0 24 12" fill="none" xmlns="http://www.w3.org/2000/svg">
                      <path d="M22 1H2L12 11L22 1Z" fill="#0A0A0A" stroke="black"/>
                  </svg>
                  <div class="dropdown-menu">
                      <ul>
                          {% if user.is_authenticated and user.profile %}
                          <li><a href="{% url 'users:user-profile' user.profile.pk %}">My profile</a></li>
                          {% endif %}
                          <li><a href="{% url 'users:logout' %}">Logout</a></li>
                      </ul>
                  </div>                 
              </div>
            {% else %}
              <div class="user-container">
                <span>Hello, guest!</span>
                <svg id="dropdown-icon" viewBox="0 0 24 12" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M22 1H2L12 11L22 1Z" fill="#0A0A0A" stroke="black"/>
                </svg>
                <div class="dropdown-menu">
                    <ul>
                        <li><a href="{% url 'users:login' %}">Login</a></li>
                        <li><a href="{% url 'users:user_signup' %}">Signup</a></li>
                    </ul>
                </div>                 
            </div>
          {% endif %}

        </nav>
    </header>

    <section class="dynamic-content-container">
      {% block content %}{% endblock content %}
    </section>
    
    <footer>
        <ul>Created by:
            <li>Tomasz Wysoczański</li>
            <li>Sebastian Bukowski</li>
            <li>Adam Smelkowski</li>
        </ul>
    </footer>
  {% block template_scripts %}
  {% endblock template_scripts %}
    <script src="{% static 'scripts.js' %}"></script>
  </body>
</html>